#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# redirect stderr to stdout so it's picked up in the docker logs
exec 2>&1
# all errors will show a line number and the command used to produce the error
SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd)/$(basename "$0")"
trap 'echo -e "[ERROR] $SCRIPT_PATH in line $LINENO when executing: $BASH_COMMAND"' ERR

APPNAME="$(hostname)/lighttpd"
APPPATH="/usr/sbin/lighttpd"
CONFIGPATH="/etc/lighttpd/lighttpd.conf"
OWNER=www-data
GROUP=www-data

[[ "$LOGLEVEL" != "ERROR" ]] && echo "[$APPNAME][$(date)] Lighttpd started as an s6 service" || true

# -----------------------------------------------------------------------------------
# Copyright 2020, 2021 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/kx1t/docker-planefence
#
# -----------------------------------------------------------------------------------
# Feel free to make changes to the variables between these two lines. However, it is
# STRONGLY RECOMMENDED to RTFM! See README.md for explanation of what these do.
#
#
# Be sure there is a /var/run/lighttpd, even with tmpfs
# The directory is defined as volatile and may thus be non-existing
# after a boot (DPM §9.3.2)

[[ ! -d /var/cache/lighttpd ]] && install -d -o $OWNER -g $GROUP -m 0750 "/var/cache/lighttpd"
[[ ! -d /var/cache/lighttpd/compress ]] && install -d -o $OWNER -g $GROUP -m 0750 "/var/cache/lighttpd/compress"
[[ ! -d /var/cache/lighttpd/uploads ]] && install -d -o $OWNER -g $GROUP -m 0750 "/var/cache/lighttpd/uploads"
[[ ! -d /var/log/lighttpd ]] &&	install -d -o $OWNER -g $GROUP -m 0750 "/var/log/lighttpd"
[[ ! -d /var/run/lighttpd ]] &&	install -d -o $OWNER -g $GROUP -m 0750 "/var/run/lighttpd"
#
# -----------------------------------------------------------------------------------
# Enable PHP / FastCGI:
[[ "$LOGLEVEL" != "ERROR" ]] && echo "[$APPNAME][$(date)] Starting FastCGI" || true
lighttpd-enable-mod fastcgi fastcgi-php >/dev/null 2>&1
#
# -----------------------------------------------------------------------------------
# Check if lighttpd is OK:
#
[[ "$LOGLEVEL" != "ERROR" ]] && echo "[$APPNAME][$(date)] Checking Lighttpd configuration" || true
$APPPATH -tt -f $CONFIGPATH || exit $?
#
# -----------------------------------------------------------------------------------
# Now run ligghttpd for real
#
[[ "$LOGLEVEL" != "ERROR" ]] && echo "[$APPNAME][$(date)] Bringing Lighttpd Up" || true
$APPPATH -f $CONFIGPATH -D
