#!/command/with-contenv bash
#shellcheck shell=bash disable=SC2015,SC1091,SC2154
# -----------------------------------------------------------------------------------
# Copyright 2020-2026 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/sdr-enthusiasts/planefence4docker/
#
# This package may incorporate other software and license terms.
# -----------------------------------------------------------------------------------
#
#sleep 1 # Give 00-container-start-time a chance to write the container start time to the file before we read it in pf-common
source /scripts/pf-common
if [[ -f /usr/share/planefence/persist/planefence.config ]]; then
    source /usr/share/planefence/persist/planefence.config
fi

"${s6wrap[@]}" echo "Initial Planefence check..."

if [[ ! -f /usr/share/planefence/persist/planefence.config ]]; then
    /usr/share/planefence/prep-planefence.sh
fi

# Post message to any old plane-alert page to inform user that Planefence has been updated
if ! chk_enabled "$PA_SHOW_STALE_PAGE"; then
    if [[ -f /usr/share/planefence/html/plane-alert/index.html ]]; then
        # Move the index to index-old.html in case someone wants to refer to it.
        mv -f /usr/share/planefence/html/plane-alert/index.html /usr/share/planefence/html/plane-alert/index-old.html
        if ! grep -q "\!-- pa_updated --" /usr/share/planefence/html/plane-alert/index-old.html; then
            sed -i "s|</h1>|</h1><h2>IMPORTANT:<br>This page is no longer maintained. To see current Plane-Alert entries, click <a href=\"index.html\">here</a>.</h2><\!-- pa_updated -->|g" /usr/share/planefence/html/plane-alert/index-old.html
            sed -i "s|<hr>Note - soon.*<hr>||g" /usr/share/planefence/html/plane-alert/index-old.html
        else
            sed -i "s|</h1>.*<\!-- pa_updated -->|</h1><h2>IMPORTANT:<br>This page is no longer maintained. To see current Plane-Alert entries, click <a href=\"index.html\">here</a>.</h2><\!-- pa_updated -->|g" /usr/share/planefence/html/plane-alert/index-old.html
        fi
    fi
else
    # Restore the old page if it exists
    if [[ -f /usr/share/planefence/html/plane-alert/index-old.html ]]; then
        mv -f /usr/share/planefence/html/plane-alert/index-old.html /usr/share/planefence/html/plane-alert/index.html
        if ! grep -q "\!-- pa_updated --" /usr/share/planefence/html/plane-alert/index.html; then
            sed -i "s|</h1>|</h1><h2>IMPORTANT:<br>This page is no longer maintained. To see current Plane-Alert entries, click <a href=\"${PF_PA_LINK:-../index.html?mode=pa}\">here</a>.</h2><\!-- pa_updated -->|g" /usr/share/planefence/html/plane-alert/index.html
            sed -i "s|<hr>Note - soon.*<hr>||g" /usr/share/planefence/html/plane-alert/index.html
        else
            sed -i "s|</h1>.*<\!-- pa_updated -->|</h1><h2>IMPORTANT:<br>This page is no longer maintained. To see current Plane-Alert entries, click <a href=\"${PF_PA_LINK:-../index.html?mode=pa}\">here</a>.</h2><\!-- pa_updated -->|g" /usr/share/planefence/html/plane-alert/index.html
        fi        
    fi
fi

if chk_disabled "${PLANEFENCE:-$PF_PLANEFENCE}" && chk_disabled "${PLANEALERT:-$PF_PLANEALERT}"; then
    log_print ERR "(PF_)PLANEFENCE and (PF_)PLANEALERT are both disabled. Container will not start!"
    exec sleep infinity
fi

"${s6wrap[@]}" echo "Initial Planefence check complete."
