#!/command/with-contenv bash
#shellcheck shell=bash disable=SC2015,SC1091,SC2154
# -----------------------------------------------------------------------------------
# Copyright 2020-2026 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/sdr-enthusiasts/planefence4docker/
#
# This package may incorporate other software and license terms.
# -----------------------------------------------------------------------------------
#

source /scripts/common

"${s6wrap[@]}" echo "Initial Planefence check..."
Checking Mastodon server and access token"

if [[ ! -f /usr/share/planefence/persist/planefence.config ]]; then
    /usr/share/planefence/prep-planefence.sh
fi

"${s6wrap[@]}" echo "Initial Planefence check done..."
