#!/command/with-contenv bash
#shellcheck shell=bash disable=SC1091,SC2174,SC2154
# -----------------------------------------------------------------------------------
# Copyright 2020-2024 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/sdr-enthusiasts/docker-planefence/
#
# This package may incorporate other software and license terms.
# -----------------------------------------------------------------------------------
#
# ATTENTION -- DO NOT MAKE THIS SCRIPT INTO A S6 DEPENDENCY FOR RUNNING PLANEFENCE
# IT SHOULD RUN AS A ONESHOT SERVICE IN PARALLEL WITH OTHER SERVICES

source "/scripts/common"

# ----------------------------
# First - householding stuff:

mkdir -p -m 0700 /usr/share/planefence/persist/.internal

savedfile="$(find "/usr/share/planefence/persist/.internal/" -name "aircraft-database-complete-*" -print0 | xargs -r -0 ls -1 -t | head -1)"
if [[ -z "$savedfile" ]]; then
  mv /usr/share/planefence/stage/aircraft-database-complete-*.csv "/usr/share/planefence/persist/.internal/" >/dev/null 2>&1 || true
  savedfile="$(find "/usr/share/planefence/persist/.internal/" -name "aircraft-database-complete-*" -print0 | xargs -r -0 ls -1 -t | head -1)"
fi
savedfile="${savedfile##*/}"
latestfile="$(curl -sL https://s3.opensky-network.org/data-samples/#metadata/ | grep -oP '(?<=\<Key\>metadata/)aircraft-database-complete.*?(?=\</Key\>)' | sort -ur | head -1)"

# Get a new version if the current one  isn't the newest:
# shellcheck disable=SC2001
savedfile_date="$(sed 's|aircraft-database-complete-\([0-9-]\+\).*$|\1|g' <<< "$savedfile")"
# shellcheck disable=SC2001
latestfile_date="$(sed 's|aircraft-database-complete-\([0-9-]\+\).*$|\1|g' <<< "$latestfile")"

if (( ${savedfile_date//-/} < ${latestfile_date//-/} )); then
  if curl -sL "https://s3.opensky-network.org/data-samples/metadata/$latestfile" > "/tmp/$latestfile"; then
    mv -f /tmp/"$latestfile" /usr/share/planefence/persist/.internal/
    ln -sf "/usr/share/planefence/persist/.internal/$latestfile" "/run/OpenSkyDB.csv"
    touch -d "31-Dec-2099" "/usr/share/planefence/persist/.internal/$latestfile" /run/OpenSkyDB.csv

    # Cleanup all but the newest OpenSkyDB files
    find /usr/share/planefence/stage/ -type f -name "aircraft-database-complete-*.csv" -printf '%T@ %p\n'| sort -g | head -n -1 | cut -d ' ' -f 2 | xargs rm -f
    find /usr/share/planefence/persist/.internal/ -type f -name "aircraft-database-complete-*.csv" -printf '%T@ %p\n'| sort -g | head -n -1 | cut -d ' ' -f 2 | xargs rm -f
    "${s6wrap[@]}" echo "Downloaded newest OpenSkyDB - $latestfile"
  else
    "${s6wrap[@]}" echo "Download of newest OpenSkyDB FAILED - $latestfile"
  fi
else
  "${s6wrap[@]}" echo "Current OpenSkyDB file ($savedfile) is up to date."
fi