#!/command/with-contenv bash
#shellcheck shell=bash disable=SC1091,SC2001,SC2174,SC2154
# -----------------------------------------------------------------------------------
# Copyright 2020-2025 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/sdr-enthusiasts/docker-planefence/
#
# This package may incorporate other software and license terms.
# -----------------------------------------------------------------------------------
#
# ATTENTION -- DO NOT MAKE THIS SCRIPT INTO A S6 DEPENDENCY FOR RUNNING PLANEFENCE
# IT SHOULD RUN AS A ONESHOT SERVICE IN PARALLEL WITH OTHER SERVICES

source "/scripts/common"
source "/usr/share/planefence/persist/planefence.config"

if chk_disabled "${OPENSKYDB_DOWNLOAD:-enabled}"; then
  "${s6wrap[@]}" echo "OpenSky Database download disabled. Skipping."
  exit 0
fi

# ----------------------------
# First - householding stuff:

mkdir -p -m 0700 /usr/share/planefence/persist/.internal

savedfile="$(find "/usr/share/planefence/persist/.internal/" -name "aircraft-database-complete-*" -print0 | xargs -r -0 ls -1 -t | head -1)"
if [[ -z "$savedfile" ]]; then
  # see if there's a OpenSky DB in the staging directory. (There probably isn't since we removed it to reduce the container size)
  mv -f /usr/share/planefence/stage/aircraft-database-complete-*.csv "/usr/share/planefence/persist/.internal/" >/dev/null 2>&1 || true
  savedfile="$(find "/usr/share/planefence/persist/.internal/" -name "aircraft-database-complete-*" -print0 | xargs -r -0 ls -1 -t | head -1)"
fi

if [[ -n "$savedfile" ]]; then
  savedfile="$(basename "$savedfile")"
  savedfile_date="$(sed 's|aircraft-database-complete-\([0-9-]\+\).*$|\1|g' <<< "$savedfile")"
else
  savedfile_date="1970-01"
fi

if ! latestfile="$(curl -sfL https://s3.opensky-network.org/data-samples/#metadata/ | grep -oP '(?<=\<Key\>metadata/)aircraft-database-complete.*?(?=\</Key\>)' | sort -ur | head -1)"; then
  "${s6wrap[@]}" echo "Cannot reach the OpenSky web server to check if a newer OpenSky DB is available. Aborting update attempt."
  if [[ ! -f /run/OpenSkyDB.csv ]] && [[ -f "/usr/share/planefence/persist/.internal/$savedfile" ]]; then
    ln -sf "/usr/share/planefence/persist/.internal/$savedfile" "/run/OpenSkyDB.csv"
  fi
  exit
fi
latestfile_date="$(sed 's|aircraft-database-complete-\([0-9-]\+\).*$|\1|g' <<< "$latestfile")"

if (( ${savedfile_date//-/} < ${latestfile_date//-/} )); then
  "${s6wrap[@]}" echo "Newer OpenSky database ($latestfile_date) available. Downloading it now"
  if curl -sfL --compressed "https://s3.opensky-network.org/data-samples/metadata/$latestfile" > "/tmp/$latestfile"; then
    find /usr/share/planefence/stage/ -type f -name "aircraft-database-complete-*.csv" -delete
    find /usr/share/planefence/persist/.internal/ -type f -name "aircraft-database-complete-*.csv" -delete
    find /usr/share/planefence/html/ -type f -name "aircraft-database-complete-*.csv" -delete
    mv -f "/tmp/$latestfile" /usr/share/planefence/persist/.internal/
    ln -sf "/usr/share/planefence/persist/.internal/$latestfile" "/run/OpenSkyDB.csv"
    "${s6wrap[@]}" echo "Downloaded newest OpenSkyDB - $latestfile"
  else
    "${s6wrap[@]}" echo "Download of newest OpenSkyDB FAILED - $latestfile"
    if [[ ! -f /run/OpenSkyDB.csv ]] && [[ -f "/usr/share/planefence/persist/.internal/$savedfile" ]]; then
      ln -sf "/usr/share/planefence/persist/.internal/$savedfile" "/run/OpenSkyDB.csv"
    fi
  fi
else
  "${s6wrap[@]}" echo "Current OpenSkyDB file ($savedfile) is up to date."
  if [[ ! -f /run/OpenSkyDB.csv ]] && [[ -f "/usr/share/planefence/persist/.internal/$savedfile" ]]; then
    ln -sf "/usr/share/planefence/persist/.internal/$savedfile" "/run/OpenSkyDB.csv"
  fi
fi
