#!/command/with-contenv bash
#shellcheck shell=bash disable=SC2015,SC1091,SC2154

source /scripts/common
# -----------------------------------------------------------------------------------
# Copyright 2020-2026 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/sdr-enthusiasts/planefence4docker/
#
# This package may incorporate other software and license terms.
# -----------------------------------------------------------------------------------
#

"${s6wrap[@]}" echo "Saving container start time"
date +%s > /run/.CONTAINER-START-TIME
