#!/command/with-contenv bash
#shellcheck shell=bash disable=SC1091,SC2154

source /scripts/common
while [[ ! -f /usr/share/planefence/persist/planefence.config ]]; do sleep 5; done


if [[ "$LOGLEVEL" != "ERROR" ]]; then "${s6wrap[@]}" echo "Get-PA-Alertlist started as an s6 service"; fi

# -----------------------------------------------------------------------------------
# Copyright 2020-2026 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/sdr-enthusiasts/docker-planefence
#
# The package contains parts of, and modifications or derivatives to the following:
# Dump1090.Socket30003 by Ted Sluis: https://github.com/tedsluis/dump1090.socket30003
# These packages may incorporate other software and license terms.
# -----------------------------------------------------------------------------------

LOOPTIME=6h

# Now let's wait a bit on the initial run to ensure that start_planefence is deployed and has finished calling prep-planefence.sh
# this ensures that the ALERTLIST parameter in /usr/share/planefence/plane-alert.conf is populated

# Note that on startup, get-pa-alertlist.sh is called from start_planefence so we don't need to do this right away.

while true
do
	if [[ "$LOGLEVEL" != "ERROR" ]]; then "${s6wrap[@]}" echo "Restarting in $LOOPTIME"; fi 
	sleep $LOOPTIME
	/usr/share/planefence/get-pa-alertlist.sh
	/usr/share/planefence/get-silhouettes.sh
 	done
