#!/command/with-contenv bash
#shellcheck shell=bash disable=SC1091,SC2015,SC2154

# -----------------------------------------------------------------------------------
# Copyright 2020-2025 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/sdr-enthusiasts/planefence4docker/
#
# The package contains parts of, and modifications or derivatives to the following:
# Dump1090.Socket30003 by Ted Sluis: https://github.com/tedsluis/dump1090.socket30003
# These packages may incorporate other software and license terms.
#
# -----------------------------------------------------------------------------------
#
# We moved the initialization sequence to /usr/share/planefence/prep-planefence.sh
# because then we can re-run the sequence if we detect changes to the config file
# Also, this time needs to be sourced otherwise it won't pick up $LOOPTIME as variables
# can't be exported back to parent processes.

source /scripts/pf-common

LOOPTIME=$(sed -n 's/\(^\s*PF_INTERVAL=\)\(.*\)/\2/p' /usr/share/planefence/persist/planefence.config)
LOOPTIME="${LOOPTIME:-60}"

PLANEFENCEDIR=/usr/share/planefence

if [[ "$LOGLEVEL" != "ERROR" ]]; then
    log_print INFO "Screenshot started as an s6 service"
fi

initial_looptime="$(( RANDOM % (LOOPTIME*2) ))"

if [[ "$LOGLEVEL" != "ERROR" ]]; then 
    log_print INFO "Planefence is deployed and will first run at $(date -d "+$initial_looptime secs" +"%F %T %Z") (in $initial_looptime secs)"
else
    log_print INFO "Planefence is deployed. Note that LOGLEVEL is set to \"ERROR\". Only failures and error messages will be written to the Docker Logs."
fi
sleep "$initial_looptime" & wait
if [[ "$LOGLEVEL" != "ERROR" ]]; then log_print INFO "Planefence starting its initial run now"; fi

while true
do
        starttime=$(date +%s)
        [[ "$LOGLEVEL" != "ERROR" ]] && log_print INFO "Starting Screenshot run..." || true
        $PLANEFENCEDIR/pf-screenshot.sh
        endtime=$(date +%s)
        [[ "$LOGLEVEL" != "ERROR" ]] && log_print INFO "Screenshot ran for $((endtime - starttime)) secs and will be running again at $(date -d @$(( starttime + LOOPTIME )) )." || true
        if (( starttime + LOOPTIME > endtime )); then
            sleep $(( (starttime + LOOPTIME) - endtime )) &
        else
            sleep 1 &
        fi
        wait
done
