#!/bin/bash
# START_PLANEFENCE - a Bash shell script to run PlaneFence in a loop
# This script is invoked by the SystemD service that keeps PlaneFence up and running
# 
# The reasons for using SystemD over CRON are several, and include
# easy of use and management
#
# To start/stop/install PlaneFence, do the following:
#
# 1 Base enablement of the PlaneFence Service from your GitHub cache:
# 	sudo cp ~/git/planefence/service/planefence.service /lib/systemd/system/
# 	sudo systemctl daemon-reload
# 	sudo systemctl enable planefence
#
# 2 Manually starting or stopping the service:
#	sudo systemctl start planefence
#	sudo systemctl stop planefence
#
# 3 Ensuring that the service is reloaded on reboot / stopping it from reloading on reboot:
#	sudo systemctl enable planefence
#	sudo systemctl disable planefence
#
# 4 Checking the status of the PlaneFence service:
#	systemctl status planefence
#
# 5 Looking at the PlaneFence logs:
#	tail -n100 -f /tmp/planefence.log
#
# -----------------------------------------------------------------------------------
# Copyright 2020 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/kx1t/planefence/
#
# The package contains parts of, and modifications or derivatives to the following:
# Dump1090.Socket30003 by Ted Sluis: https://github.com/tedsluis/dump1090.socket30003
# These packages may incorporate other software and license terms.
#
# -----------------------------------------------------------------------------------
# Feel free to make changes to the variables between these two lines. However, it is
# STRONGLY RECOMMENDED to RTFM! See README.md for explanation of what these do.
#
# LOOPTIME is the time between two runs of PlaneFence (in seconds)
# Do not set this to less than about 120 seconds as it will overload your system
LOOPTIME=80
#
# PLANEFENCEDIR contains the directory where planefence.sh is location 
PLANEFENCEDIR=/usr/share/planefence
# -----------------------------------------------------------------------------------

while true
do
	$PLANEFENCEDIR/planefence.sh >/tmp/planefence.log
	sleep $LOOPTIME
done

