#!/bin/bash
#!/command/with-contenv bash
#shellcheck shell=bash disable=SC2034

# -----------------------------------------------------------------------------------
# Copyright 2025 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://sdr-e.com/docker-planefence/

#
# This package may incorporate other software and license terms.
# -----------------------------------------------------------------------------------

# Convert a string to ASCII
# This function converts a string to ASCII by replacing all non-ASCII characters
# with their ASCII equivalent. This is useful for converting special characters
# in names to their ASCII equivalent.

function to_ascii() {
  local string="$1"
  local char

  declare -A conv conv2
  # Add all unique conversions here

  conv[ÀÁÂÃÄÅĀĂĄǍǞǠȀȂȦ]="A"
  conv[ÇČĆĈĊ]="C"
  conv[ĎĐḊḌḎḐḒ]="D"
  conv[ÈÉÊËĒĔĘĖĚȄȆ]="E"
  conv[ĜĞĢĠ]="G"
  conv[ĤĦḢḤḦḨḪ]="H"
  conv[ÌÍÎÏĨĪĬĮİ]="I"
  conv[Ĵ]="J"
  conv[ĶḰḲḴ]="K"
  conv[ĹĻĽŁḶḸḺḼ]="L"
  conv[ḾṀṂ]="M"
  conv[ÑŃŅŇŊṄṆṈṊ]="N"
  conv[ÒÓÔÕÖØŌŎŐ]="O"
  conv[ŔŖŘṘṚṜ]="R"
  conv[ŚŜŞŠṠṢṤṦṨ]="S"
  conv[ŢŤŦṪṬṮṰ]="T"
  conv[ÙÚÛÜŪŬŮŰŲŨṲṴṶṸṺ]="U"
  conv[ŴẀẂẄẆ]="W"
  conv[ÝŶŸẎỲỴỶỸ]="Y"
  conv[ŹŻŽẐẒẔ]="Z"

  conv[àáâãäåāăąǎǟǡǻȁȃȧ]="a"
  conv[ḃḅḇ]="b"
  conv[çčĉċć]="c"
  conv[ďđḋḍḏḑḓ₫]="d"
  conv[èéêëēĕėęěȅȇ]="e"
  conv[ḟƒ]="f"
  conv[ĝğģġ]="g"
  conv[ĥħḣḥḧḩḫẖ]="h"
  conv[ìíîïĩīĭįıɨᵻ]="i"
  conv[ĵǰ]="j"
  conv[ķĸḱḳḵ]="k"
  conv[ĺļľłḷḹḻḽ]="l"
  conv[ṁṃḿ]="m"
  conv[ñńņňŋṅṇṉṋ]="n"
  conv[òóôõöøōŏő]="o"
  conv[ŕŗřṙṛṝ]="r"
  conv[śŝşšṡṣṥṧṩʃ]="s"
  conv[ţťŧṫṭṯṱẗ]="t"
  conv[ùúûüūŭůűųũṳṵṷṹṻ]="u"
  conv[ŵẁẃẅẇ]="w"
  conv[ýÿŷẏẙỳỵỷỹĳ]="y"
  conv[źżžẑẓẕ]="z"

  conv[æ]="ae"
  conv[œ]="oe"
  conv[ß]="ss"
  conv[þ]="th"
  conv[ð]="dh"

  conv2[" & "]=" AND "
  conv2["&AMP;"]=" AND "

  for char in "${!conv[@]}"; do
    string="${string//[$char]/${conv[$char]}}"
  done
  
  for char in "${!conv2[@]}"; do
    string="${string//$char/${conv[$char]}}"
  done

  echo "${string//[^[:alnum:] ]/}" | xargs

}

if [[ -z "$1" ]]; then
  echo "Usage: $0 <string>"
  exit 1
fi

to_ascii "$1"
