#lighttpd configuration for planefence

# redirect Plane-Alert landing paths to the main index in PA mode
url.redirect += (
  "^/plane-alert/?$" => "/index.html?mode=pa",
  "^/plane-alert/index\.html$" => "/index.html?mode=pa"
)

alias.url += (
  "/plane-alert/" => "/usr/share/planefence/html/plane-alert/"
)
