#!/usr/bin/with-contenv bash
#shellcheck shell=bash disable=SC2015

APPNAME="$(hostname)/check-mastodon"
# -----------------------------------------------------------------------------------
# Copyright 2020-2022 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/kx1t/planefence4docker/
#
# This package may incorporate other software and license terms.
# -----------------------------------------------------------------------------------
#

echo "[$(date)][$APPNAME] Checking Mastodon server and access token"

MASTODON_SERVER="$(sed -n 's/\s*MASTODON_SERVER=\(.*\)/\1/p' /usr/share/planefence/persist/planefence.config)"
MASTODON_ACCESS_TOKEN="$(sed -n 's/\s*MASTODON_ACCESS_TOKEN=\(.*\)/\1/p' /usr/share/planefence/persist/planefence.config)"

if [[ -z "$MASTODON_ACCESS_TOKEN" ]] || [[ -z "$MASTODON_SERVER" ]]
then
    echo "[$(date)][$APPNAME] Mastodon not configured"
    exit 0
else
    MASTODON_SERVER="${MASTODON_SERVER,,}"
    # strip http:// https://
    [[ "${MASTODON_SERVER:0:7}" == "http://" ]] && MASTODON_SERVER="${MASTODON_SERVER:7}" || true
    [[ "${MASTODON_SERVER:0:8}" == "https://" ]] && MASTODON_SERVER="${MASTODON_SERVER:8}" || true
    if curl -sS -H "Authorization: Bearer $MASTODON_ACCESS_TOKEN" "https://${MASTODON_SERVER}/api/v1/apps/verify_credentials" | grep -vi "The access token is invalid" >/dev/null 2>&1
    then
        echo "[$(date)][$APPNAME] Mastodon configured correctly."
        touch /run/mastodon_ok
    else
        echo "[$(date)][$APPNAME] Mastodon configured incorrectly. Check your setup"
        rm -f /run/mastodon_ok
    fi
fi
